name: Simple Bank Project CI

on:
  push:
    branches: [ master ]
  
jobs:
  
  test:
    name: Test 
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: mysecret
          POSTGRES_USER: root
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
  
    - name: Migrate CLI installation
      run: |
       curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
       sudo mv migrate /usr/bin/
       which migrate

    - name: Checking out code
      uses: actions/checkout@v2

    - name: DB migration
      run: make migrateup  
      
    - name: Test
      run: make test 
