name: Simple Bank Project CI

on:
  push:
    branches: [ master ]
  
jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_PASSWORD: mysecret
          POSTGRES_USER: root
          POSTGRES_DB: simplebank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
  
    - name: Checking out code
      uses: actions/checkout@v2

    - name: DB migration
      uses: make migrateup  
      
    - name: Test
      run: make test 
